### ISSUE TITLE
how to get onnx file for gan model

### ISSUE THREAD

**Issue by ghost** [gohar-malik/onnxjs-gan#1]
Hi how do you get onnx file for a gan model here https://github.com/taki0112/UGATIT

**Comment by gohar-malik** [comment]
Hi @ak9250  
The link you have given is a Tensorflow implementation. I would suggest using the Pytorch Implementation instead, using this link https://github.com/znxlwm/UGATIT-pytorch.
Pytorch has built-in functionality to export models (`torch.nn.Module` Object) as onnx models using  `torch.onnx.export()` method. You can find more info on this link https://pytorch.org/docs/stable/onnx.html.

**Comment by ghost** [comment]
@gohar-malik thanks are you able to get it working I tried and ran into some errors

**Comment by gohar-malik** [comment]
@ak9250 At what part are you running into errors?

**Comment by ghost** [comment]
@gohar-malik I am getting a system error after setting up the torch model and model url, I think the args are not passed in correctly

**Comment by gohar-malik** [comment]
@ak9250 Can you share your code snippet and screenshot of the error here?

**Comment by ghost** [comment]
@gohar-malik I am using this implementation as the one you linked does not have pretrained weights https://github.com/minivision-ai/photo2cartoon

**Comment by gohar-malik** [comment]
@ak9250 Can you tell me exactly what problem are you facing?
