### ISSUE TITLE
Do you have the code for the pytorch training and model export?

### ISSUE THREAD

**Issue by deinnielle** [gohar-malik/onnxjs-gan#2]
Hi, I would like to look at the pytorch training and model export can you add it to the repo?

**Comment by gohar-malik** [comment]
Hi @deinnielle 

There are many tutorials online, that can help you to train your own PyTorch Vanilla GAN model on MNIST. I personally trained the model using this tutorial:
https://medium.com/ai-society/gans-from-scratch-1-a-deep-introduction-with-code-in-pytorch-and-tensorflow-cb03cdcdba0f

And for model export, you only need a couple of lines of code for PyTorch. Any trained Pytorch model (`torch.nn.Module` object) can be exported using these lines:
`dummy_input = torch.randn(1, 100)`
`torch.onnx.export(model, dummy_input, "./onnx/VanillaGAN_Mnist.onnx")`
You can find all the relevant information here:
https://pytorch.org/docs/stable/onnx.html
